### PR TITLE
Scroll to bottom when chat log exceeds screen height (#7)

### PR DESCRIPTION
**Pull request by heejongahn**
I'm not sure if adding `Noop` Msg is best practice. Will fix as soon as I find better option.

### CODE REVIEW

**Comment by simnalamburt** [comment]
@heejongahn 

The name of the type that I deliberately named as `Action` in `Msg` is back to `Msg` again, is there a reason? Refer to https://github.com/openirc/openirc/commit/7de7486b6aa2ef809ce088558913b687b532ac40 's commit message for the reason named `Action`

**Comment by heejongahn** [comment]
@simnalamburt I thought it would be better to follow the official documents, as it could reduce confusion when new contributors join the project. I agree that using `Msg` might also lead to confusion, but I would prefer to follow the community standard.

**Comment by simnalamburt** [comment]
@heejongahn Then, please suggest other English words to replace `Message` which means user's conversation.

**Comment by heejongahn** [comment]
@simnalamburt For now, `Line` or `Log` comes to my mind. Especially when we're already using `logs` for `List Message`.

**Comment by simnalamburt** [comment]
Choosed `Line`.

**Pull request merged**
